<?php
    echo '<article>
        <h2>Orígenes de la Mezquita de Córdoba</h2>
        
        <img src="images/mezquita.jpg" alt="Interior de la Mezquita de Córdoba">
        <p>Se empezó a construir como mezquita en el año 786, con la apropiación por los conquistadores musulmanes de la basílica hispanorromana de <a href="https://es.wikipedia.org/wiki/Bas%C3%ADlica_de_San_Vicente_M%C3%A1rtir" target="_blank">San Vicente Mártir</a> y la reutilización de parte de los materiales, quedando reservada al culto musulmán. El edificio resultante fue objeto de ampliaciones durante el Emirato de Córdoba y el Califato de Córdoba. Con 23 400 metros cuadrados, fue la segunda mezquita más grande del mundo en superficie, por detrás de la Mezquita de La Meca, siendo sólo alcanzada posteriormente por la Mezquita Azul (Estambul, 1588). Una de sus principales características es que su muro de la qibla no fue orientado hacia La Meca, sino 51º grados más hacia el sur, algo habitual en las mezquitas de al-Ándalus.</p>
        <p>Tras la llegada del islam a la península, en el año 714, Muza estableció el reparto del conjunto basilical, en el pacto de capitulación, por el que una parte se dedicó al culto islámico y en otra permaneció el culto cristiano, comprometiéndose a respetar la parte cristiana de la basílica mientras se pagasen los tributos exigidos. Dicha convivencia fue difícil, y no siempre se respetó el compromiso. Así, durante los conflictos entre yemeníes y muladíes en el año 748, las autoridades musulmanas emplearon la parte cristiana para el juicio y condena a muerte de los cabecillas de los yemeníes. Según una versión sucinta del relato tradicional, la mezquita de Córdoba habría sido iniciada bajo el reinado del primer emir omeya <a href="https://es.wikipedia.org/wiki/Abderram%C3%A1n_I" target="_blank">Abderramán I</a> entre el 780 y el 785, sobre la planta de la iglesia cristiana, cambiando la orientación de su eje. Sufrió sucesivas ampliaciones en los siglos IX y X y fue concluida bajo mandato de <a href="https://es.wikipedia.org/wiki/Almanzor" target="_blank">Almanzor</a>. La más importante de las ampliaciones es la de Alhakén II a la que pertenecen los arcos del mihrab. En estos arcos se puede ver la evolución de la construcción: las columnas visigodas con sus arcos de herradura les resultaron demasiado bajos a los musulmanes por lo que decidieron añadir pilares sobre las columnas y disponer arcos más altos sin derribar los anteriores y policromando en rojo y blanco todos con lo que se construyó la célebre y más conocida imagen de la Mezquita de Córdoba. Fue lugar de reuniones a la vez religiosas y políticas pues podía albergar hasta veinte mil personas.</p>
        <p>El inicio de su construcción se debe al primer emir omeya de Córdoba, haciéndose sobre el emplazamiento de la basílica visigoda de <a href="https://es.wikipedia.org/wiki/Bas%C3%ADlica_de_San_Vicente_M%C3%A1rtir" target="_blank">San Vicente Mártir</a>, iglesia construida en el siglo VI, en cuyo solar se inicia la edificación del oratorio o haram en el año 786.</p>
        <p>Este primer edificio consta, en cualquier caso, de once naves longitudinales orientadas hacia el río Guadalquivir, cuya anchura es idéntica, a excepción de la central, que conduce al mihrab y las dos de los extremos. La central ligeramente más ancha que el resto y las laterales ligeramente más estrechas, aunque estas leves diferencias solo son apreciables en un plano. Estas naves constan de doce intercolunios que corren en dirección al muro de la quibla.</p>
    </article>
    <article>
        <h2>El Patio de los Naranjos</h2>
        <p>El patio de los Naranjos está situado en la parte norte del templo. Tiene su origen en el patio de abluciones de la mezquita de Abderramán I, siendo posteriormente ampliado y reformado durante las siguientes etapas constructivas. Recibe su nombre de los 98 naranjos que contiene, que fueron plantados formando hileras a finales del siglo XVIII.</p>
        <p>Se trata de un recinto cerrado de 130 metros de largo por 50 de ancho. Sus lados occidental, septentrional y oriental se hallan rodeados de galerías porticadas y cuentan con seis puertas que comunican al patio con el exterior: la puerta de los Deanes y el postigo de la Leche en su lado oeste; la puerta del Perdón y la del Caño Gordo al norte; y la puerta de la Grada Redonda y la de Santa Catalina al este. En estas galerías se hayan expuestas las vigas y tablones que conformaban el artesonado original del templo, procedentes de la restauración del siglo XIX. Su estado de conservación, relativamente bueno al ser todavía visibles los relieves que las decoraban y parte de la policromía original, motivaron su retirada para una mejor conservación y sirvieron de modelo para la realización de las que actualmente se ven.</p>
        <p>Su muro sur, que comunica al patio con el interior del templo, está formado por 17 arcos de herradura. Estos arcos se encontraban originariamente abiertos, haciendo de la sala de oración un espacio abierto. Hoy en día sólo uno de ellos, la puerta de las Palmas, comunica con el patio. Todos los arcos al este de la puerta fueron tapiados hace tiempo para alojar en ellos múltiples capillas. Por contra, los arcos al oeste de la puerta se hallan cerrados por celosías de estilo arábigo construidas en los años 70 por el arquitecto Rafael de La-Hoz Arderius.</p>
    </article>';
?>